version: "3.8"

# copy .env to .env.docker
# run docker-compose --env-file=.env.docker up -d

services:
  main_service:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: service_pgsql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - service_pgsql

  service_pgsql:
    image: postgres:12.6-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
