#!/bin/bash

# ENVIRONMENT VARIABLES ----------------------------------
	cp /sistema-ventas/.env.example /sistema-ventas/.env

# MIGRATIONS -----------------------------------
	echo 'Running Migrations...'
	cd /sistema-ventas
	composer dump-autoload
	php artisan key:generate
	php artisan migrate:fresh --seed --force -n
    php artisan config:cache
	echo 'Migrations done!'

# APACHE -----------------------------------
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi
exec "$@"
